baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'VR Locomotion'
subtitle = 'by Björn Welker'
theme='github-style' 
pygmentsCodeFences = true
pygmentsUseClasses = true
 
 [params]
  author = "Björn Welker"
  description = "Student of Visual Computing"
  github = "br0wnbeer"
  email = "bjoern.welker@gmail.com"
  lastmod = true
  userStatusEmoji = ""
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "Germany"
  enableGitalk = false

  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = "repo"
    owner = "MeiK2333"
    admin = "MeiK2333"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/br0wnbeer"


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"
